/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    sources: Source;
    variants: Variant;
    'slug-history': SlugHistory;
    categories: Category;
    'source-snapshots': SourceSnapshot;
    'phase-tasks': PhaseTask;
    'acceptance-criteria': AcceptanceCriterion;
    'activity-log': ActivityLog;
    tools: Tool;
    clicks: Click;
    opportunities: Opportunity;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    sources: SourcesSelect<false> | SourcesSelect<true>;
    variants: VariantsSelect<false> | VariantsSelect<true>;
    'slug-history': SlugHistorySelect<false> | SlugHistorySelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'source-snapshots': SourceSnapshotsSelect<false> | SourceSnapshotsSelect<true>;
    'phase-tasks': PhaseTasksSelect<false> | PhaseTasksSelect<true>;
    'acceptance-criteria': AcceptanceCriteriaSelect<false> | AcceptanceCriteriaSelect<true>;
    'activity-log': ActivityLogSelect<false> | ActivityLogSelect<true>;
    tools: ToolsSelect<false> | ToolsSelect<true>;
    clicks: ClicksSelect<false> | ClicksSelect<true>;
    opportunities: OpportunitiesSelect<false> | OpportunitiesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale:
    ('false' | 'none' | 'null') | false | null | ('en' | 'ms' | 'th' | 'vi') | ('en' | 'ms' | 'th' | 'vi')[];
  globals: {};
  globalsSelect: {};
  locale: 'en' | 'ms' | 'th' | 'vi';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  roles?: ('admin' | 'editor' | 'reviewer')[] | null;
  reviewLocales?: ('en' | 'ms' | 'th' | 'vi')[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sources".
 */
export interface Source {
  id: number;
  /**
   * Immutable ULID. Cross-locale key. Never reuse or change.
   */
  contentId: string;
  type:
    | 'tutorial'
    | 'prompt_page'
    | 'prompt'
    | 'collection'
    | 'tool'
    | 'compare_platform'
    | 'compare_tools'
    | 'review'
    | 'role_page'
    | 'blog_post'
    | 'community_post'
    | 'free_tool'
    | 'article';
  sourceVersion: number;
  /**
   * { fieldKey: sha256 } for field-level change detection.
   */
  fieldHashes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Public source URL (in-scope only). Never a gated URL.
   */
  sourceUrl?: string | null;
  difficulty?: ('beginner' | 'intermediate' | 'advanced') | null;
  datePublished?: string | null;
  dateModified?: string | null;
  image?: (number | null) | Media;
  /**
   * Informational badge only. Gated video is OUT OF SCOPE (docs/specs/01 §5).
   */
  hasVideo?: boolean | null;
  /**
   * Type-specific language-neutral fields (enums, refs, config).
   */
  neutralData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Edges to other entities by contentId. Resolved to locale slugs at render.
   */
  relationships?:
    | {
        /**
         * e.g. tool, related, step, category, role, prompt
         */
        rel: string;
        targetContentId: string;
        /**
         * For ordered rels (e.g. collection steps).
         */
        order?: number | null;
        id?: string | null;
      }[]
    | null;
  ingestStatus?: ('extracted' | 'structured' | 'error') | null;
  lastIngestRunId?: string | null;
  lifecycleStatus?: ('active' | 'source_missing' | 'review_required' | 'unpublished' | 'archived') | null;
  sourceMissingSince?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants".
 */
export interface Variant {
  id: number;
  /**
   * FK to sources.contentId (cross-locale key).
   */
  contentId: string;
  locale: 'en' | 'ms' | 'th' | 'vi';
  /**
   * Mirror of the source type (denormalized for queries).
   */
  type:
    | 'tutorial'
    | 'prompt_page'
    | 'prompt'
    | 'collection'
    | 'tool'
    | 'compare_platform'
    | 'compare_tools'
    | 'review'
    | 'role_page'
    | 'blog_post'
    | 'community_post'
    | 'free_tool'
    | 'article';
  status: 'draft' | 'mt_generated' | 'in_review' | 'approved' | 'published' | 'archived';
  publishedAt?: string | null;
  title: string;
  /**
   * Localized, unique per (locale,type). Slug changes recorded in slug-history for 301s.
   */
  slug: string;
  /**
   * Short localized summary / TL;DR (public).
   */
  summary?: string | null;
  /**
   * Structured localized content blocks: [{ id, heading, body?, items?[] }]. PUBLIC content only — gated Instructions are OUT OF SCOPE and never stored here.
   */
  sections?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Localized FAQ: [{ id, q, a }].
   */
  faq?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Optional rich body (unused by the pilot; sections[] is the structured path).
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * { recommendedTools: [{ toolSlug, why, cta }] } — disclosed affiliate CTAs. Empty when there is no genuine commercial opportunity.
   */
  commerce?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
    noindex?: boolean | null;
  };
  /**
   * Managed by the translation pipeline (docs/specs/03). English (source) variants leave these at defaults.
   */
  translation?: {
    /**
     * sources.sourceVersion this was translated from. If < current → stale.
     */
    translatedFromSourceVersion?: number | null;
    translationVersion?: number | null;
    localizationVersion?: number | null;
    /**
     * { fieldKey: 0..1 } confidence scores (docs/specs/03 §H).
     */
    confidence?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * { fieldKey: state } per-field translation status (docs/specs/03 §E).
     */
    fieldStatus?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    stale?: boolean | null;
    reviewer?: (number | null) | User;
    reviewNotes?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "slug-history".
 */
export interface SlugHistory {
  id: number;
  contentId: string;
  locale: 'en' | 'ms' | 'th' | 'vi';
  type: string;
  oldSlug: string;
  newSlug: string;
  changedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  /**
   * Stable language-neutral key (e.g. 'marketing').
   */
  key: string;
  kind: 'course_category' | 'tool_category' | 'role';
  label: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "source-snapshots".
 */
export interface SourceSnapshot {
  id: number;
  contentId?: string | null;
  sourceUrl: string;
  sourceType?: string | null;
  sourceIdentifier?: string | null;
  retrievedAt: string;
  /**
   * Hash of the fetched public HTML.
   */
  rawHash?: string | null;
  httpStatus?: number | null;
  scopeDecision?: ('in-scope' | 'out-of-scope') | null;
  extractionStatus?: ('ok' | 'partial' | 'failed') | null;
  /**
   * { field: status } per-field extraction outcome.
   */
  fieldCoverage?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Structured English representation (presentation-independent). Never raw source HTML.
   */
  normalizedSnapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "phase-tasks".
 */
export interface PhaseTask {
  id: number;
  phase: string;
  area: 'translation' | 'seo' | 'qa' | 'extraction' | 'infra' | 'dashboard' | 'launch';
  title: string;
  status: 'todo' | 'in_progress' | 'blocked' | 'done';
  priority: 'high' | 'medium' | 'low';
  blockedBy?: string | null;
  evidence?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "acceptance-criteria".
 */
export interface AcceptanceCriterion {
  id: number;
  phase: string;
  area?: string | null;
  criterion: string;
  result: 'pass' | 'fail' | 'not_verified';
  evidence?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity-log".
 */
export interface ActivityLog {
  id: number;
  /**
   * system | editor:<id>
   */
  actor: string;
  action: string;
  entity?: string | null;
  locale?: string | null;
  detail?: string | null;
  outcome?: ('ok' | 'failed' | 'review_required') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tools".
 */
export interface Tool {
  id: number;
  name: string;
  /**
   * Stable key used in /go/<slug>.
   */
  slug: string;
  vendor?: string | null;
  /**
   * Canonical official product URL (used when no affiliate link).
   */
  officialUrl: string;
  category?: string | null;
  audience?: string | null;
  useCases?: string | null;
  pricingSummary?: string | null;
  hasFreePlan?: boolean | null;
  affiliateStatus?: ('none' | 'available' | 'pending' | 'closed') | null;
  /**
   * Verified affiliate/tracking URL. Empty → /go falls back to officialUrl.
   */
  affiliateUrl?: string | null;
  commissionType?: ('recurring_pct' | 'onetime_pct' | 'flat' | 'unknown') | null;
  /**
   * e.g. '25%' or 'USD 50'. Free text — never assume permanence.
   */
  commissionValue?: string | null;
  recurring?: boolean | null;
  /**
   * e.g. '45 days'.
   */
  cookieDuration?: string | null;
  disclosureRequired?: boolean | null;
  /**
   * Evidence for the affiliate terms (official affiliate page). REQUIRED to claim a program.
   */
  sourceUrl?: string | null;
  /**
   * When affiliate terms were last verified. Stale → re-verify before trusting.
   */
  lastVerifiedAt?: string | null;
  /**
   * Include in recommendations. Turn off when a program closes.
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clicks".
 */
export interface Click {
  id: number;
  /**
   * tools.slug that was clicked.
   */
  tool: string;
  /**
   * contentId of the source article (if known).
   */
  article?: string | null;
  /**
   * Path/URL the click came from (referer).
   */
  sourcePage?: string | null;
  locale?: string | null;
  /**
   * Where the click was redirected (affiliate or official).
   */
  destination?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "opportunities".
 */
export interface Opportunity {
  id: number;
  topic: string;
  candidateKeyword?: string | null;
  language?: ('en' | 'ms' | 'th' | 'vi') | null;
  country?: string | null;
  searchIntent?: ('informational' | 'commercial' | 'transactional' | 'navigational') | null;
  commercialIntent?: ('NOT_AVAILABLE' | 'low' | 'medium' | 'high') | null;
  freshness?: ('NOT_AVAILABLE' | 'low' | 'medium' | 'high') | null;
  /**
   * Observed evidence (e.g. autocomplete, forum volume). NOT invented numbers.
   */
  demandEvidence?: string | null;
  /**
   * What the SERP looks like (who ranks, AIO present?).
   */
  serpObservation?: string | null;
  competitionObservation?: ('NOT_AVAILABLE' | 'low' | 'medium' | 'high') | null;
  affiliatePotential?: ('NOT_AVAILABLE' | 'low' | 'medium' | 'high') | null;
  naluUniqueness?: ('NOT_AVAILABLE' | 'low' | 'medium' | 'high') | null;
  confidence?: ('low' | 'medium' | 'high') | null;
  decision?: ('considering' | 'pursue' | 'parked' | 'rejected' | 'published') | null;
  sourceUrls?:
    | {
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  lastCheckedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'sources';
        value: number | Source;
      } | null)
    | ({
        relationTo: 'variants';
        value: number | Variant;
      } | null)
    | ({
        relationTo: 'slug-history';
        value: number | SlugHistory;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'source-snapshots';
        value: number | SourceSnapshot;
      } | null)
    | ({
        relationTo: 'phase-tasks';
        value: number | PhaseTask;
      } | null)
    | ({
        relationTo: 'acceptance-criteria';
        value: number | AcceptanceCriterion;
      } | null)
    | ({
        relationTo: 'activity-log';
        value: number | ActivityLog;
      } | null)
    | ({
        relationTo: 'tools';
        value: number | Tool;
      } | null)
    | ({
        relationTo: 'clicks';
        value: number | Click;
      } | null)
    | ({
        relationTo: 'opportunities';
        value: number | Opportunity;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  reviewLocales?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sources_select".
 */
export interface SourcesSelect<T extends boolean = true> {
  contentId?: T;
  type?: T;
  sourceVersion?: T;
  fieldHashes?: T;
  sourceUrl?: T;
  difficulty?: T;
  datePublished?: T;
  dateModified?: T;
  image?: T;
  hasVideo?: T;
  neutralData?: T;
  relationships?:
    | T
    | {
        rel?: T;
        targetContentId?: T;
        order?: T;
        id?: T;
      };
  ingestStatus?: T;
  lastIngestRunId?: T;
  lifecycleStatus?: T;
  sourceMissingSince?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants_select".
 */
export interface VariantsSelect<T extends boolean = true> {
  contentId?: T;
  locale?: T;
  type?: T;
  status?: T;
  publishedAt?: T;
  title?: T;
  slug?: T;
  summary?: T;
  sections?: T;
  faq?: T;
  body?: T;
  commerce?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
        noindex?: T;
      };
  translation?:
    | T
    | {
        translatedFromSourceVersion?: T;
        translationVersion?: T;
        localizationVersion?: T;
        confidence?: T;
        fieldStatus?: T;
        stale?: T;
        reviewer?: T;
        reviewNotes?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "slug-history_select".
 */
export interface SlugHistorySelect<T extends boolean = true> {
  contentId?: T;
  locale?: T;
  type?: T;
  oldSlug?: T;
  newSlug?: T;
  changedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  key?: T;
  kind?: T;
  label?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "source-snapshots_select".
 */
export interface SourceSnapshotsSelect<T extends boolean = true> {
  contentId?: T;
  sourceUrl?: T;
  sourceType?: T;
  sourceIdentifier?: T;
  retrievedAt?: T;
  rawHash?: T;
  httpStatus?: T;
  scopeDecision?: T;
  extractionStatus?: T;
  fieldCoverage?: T;
  normalizedSnapshot?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "phase-tasks_select".
 */
export interface PhaseTasksSelect<T extends boolean = true> {
  phase?: T;
  area?: T;
  title?: T;
  status?: T;
  priority?: T;
  blockedBy?: T;
  evidence?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "acceptance-criteria_select".
 */
export interface AcceptanceCriteriaSelect<T extends boolean = true> {
  phase?: T;
  area?: T;
  criterion?: T;
  result?: T;
  evidence?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity-log_select".
 */
export interface ActivityLogSelect<T extends boolean = true> {
  actor?: T;
  action?: T;
  entity?: T;
  locale?: T;
  detail?: T;
  outcome?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tools_select".
 */
export interface ToolsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  vendor?: T;
  officialUrl?: T;
  category?: T;
  audience?: T;
  useCases?: T;
  pricingSummary?: T;
  hasFreePlan?: T;
  affiliateStatus?: T;
  affiliateUrl?: T;
  commissionType?: T;
  commissionValue?: T;
  recurring?: T;
  cookieDuration?: T;
  disclosureRequired?: T;
  sourceUrl?: T;
  lastVerifiedAt?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clicks_select".
 */
export interface ClicksSelect<T extends boolean = true> {
  tool?: T;
  article?: T;
  sourcePage?: T;
  locale?: T;
  destination?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "opportunities_select".
 */
export interface OpportunitiesSelect<T extends boolean = true> {
  topic?: T;
  candidateKeyword?: T;
  language?: T;
  country?: T;
  searchIntent?: T;
  commercialIntent?: T;
  freshness?: T;
  demandEvidence?: T;
  serpObservation?: T;
  competitionObservation?: T;
  affiliatePotential?: T;
  naluUniqueness?: T;
  confidence?: T;
  decision?: T;
  sourceUrls?:
    | T
    | {
        url?: T;
        id?: T;
      };
  lastCheckedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}